[package]

name = "mail-todo"
version = "0.0.1"
authors = [ "Miquel Ruiz <mruiz@cpan.org>" ]

[dependencies]

glib = "*"
#imap = "0.0.6"
imap = { git = "https://github.com/miquelruiz/rust-imap.git" }
openssl = "*"
regex = "*"
notify-rust = "*"

[dependencies.gtk]
version = "*"
features = ["v3_10"]
