[package]

name = "mail-todo"
version = "0.0.1"
authors = [ "Miquel Ruiz <mruiz@cpan.org>" ]

[dependencies]

getopts = "*"
glib = "*"
#imap = "0.0.6"
imap = { git = "https://github.com/miquelruiz/rust-imap.git" }
notify-rust = "*"
openssl = "*"
regex = "*"
time = "*"

[dependencies.gtk]

version = "*"
features = ["v3_10"]
