[package]

name = "mail-todo"
version = "0.0.1"
authors = [ "Miquel Ruiz <mruiz@cpan.org>" ]

[dependencies]

env_logger = "*"
glib = "*"
email = "*"
getopts = "*"
#imap = "0.0.6"
imap = { git = "https://github.com/miquelruiz/rust-imap.git" }
log = "*"
libresolv-sys = { path = "libresolv-sys", version = "0.1.0" }
openssl = "0.7.14"
regex = "*"
notify-rust = "*"

[dependencies.gtk]
version = "*"
features = ["v3_10"]
